### ISSUE TITLE
31.4.0 is not on npm (yet)

### ISSUE THREAD

**Issue by corneliusroemer** [electron/mksnapshot#127]
I saw there's a Github release for v31.4.0 but it doesn't seem to be on npm yet

https://www.npmjs.com/package/electron-mksnapshot?activeTab=versions

**Comment by dsanders11** [comment]
@corneliusroemer, it should be published on npm now. Sorry about that, we were updating our release infrastructure and got blocked on an issue which took a bit to resolve.

**Comment by corneliusroemer** [comment]
No worries! While you're at it - can you have a look at https://github.com/electron/mksnapshot/issues/123 ? If I'm understanding the upstream chromium issue correctly it might mean the mksnapshot is broken for pretty much everything and everyone using electron >=29? Is that really possible - because no one else has reported anything here yet. Maybe no one uses mksnapshot or people don't update electron?
