### ISSUE TITLE
Version mismatch between V8 binary and snapshot

### ISSUE THREAD

**Issue by 5eraph** [electron/mksnapshot#29]
Hi, I got following error on app startup:
```
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 8.0.426.27-electron.0
#    Snapshot version: 8.0.426.16-electron.0
```
electron version: `8.3.0`
electron-mksnapshot: `8.0.0`

Do you have any suggestions how to proceed?

**Comment by DeeDeeG** [comment]
I'm guessing a bit, but I think there needs to be a new release on this repo close enough to the electron version you are looking for.

For your use-case, it should be exactly `8.3.0` to avoid guessing or doing more research when the V8 version was changed upstream in the main Electron project.

I am seeing a similar issue at the Atom repo. https://github.com/atom/atom/pull/20764#issuecomment-632977436

**Comment by jkleinsc** [comment]
@DeeDeeG @5eraph this package should be updated to handle custom electron versions like chromedriver now does: https://github.com/electron/chromedriver#overriding-the-version-downloaded.

In the meantime, the manual resolution would be to download the correct `mksnapshot` version from https://github.com/electron/electron/releases, eg for 8.3.0, download from https://github.com/electron/electron/releases/tag/v8.3.0.  Unzip the contents to `node_modules/electron-mksnapshot/bin` and you should now have the proper version of mksnapshot available.

**Comment by DeeDeeG** [comment]
@jkleinsc thank you for the quick reply!

> @DeeDeeG @5eraph this package should be updated to handle custom electron versions like chromedriver now does: https://github.com/electron/chromedriver#overriding-the-version-downloaded.

Basically re-implementing this PR (https://github.com/electron/chromedriver/pull/59) from electron-chromedriver but at this repo instead?

I would be willing to give that a try if it would be helpful, post the PR if it works.

**Comment by jkleinsc** [comment]
@DeeDeeG - https://github.com/electron/mksnapshot/pull/30

**Comment by DeeDeeG** [comment]
Very cool, thank you!

Will see if I can convince the Atom folks to use this (once that PR merges here).

**Comment by DeeDeeG** [comment]
One last thing, it would be really neat to have this as a release at the npmjs.com registry, but short of that I can depend on a GitHub URL for this package.

**Comment by jkleinsc** [comment]
@DeeDeeG @5eraph update to electron-mksnapshot v9.0.2 and you can now use `ELECTRON_CUSTOM_VERSION` to download the correct version.

**Comment by 5eraph** [comment]
Nice job, thank you.
