### ISSUE TITLE
snapshotResult is not defined with Electron 11

### ISSUE THREAD

**Issue by QuiiBz** [electron/mksnapshot#37]
Hi, I tried implementing v8 snapshots with Electron 11 on Apple Silicon devices.

The `snapshot_blob.bin` is successfully created, and I then move it to the `node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Resources` folder.

But when starting the app, I got an error telling me that `snapshotResult` was not defined. I followed this [blog post](https://blog.inkdrop.info/how-to-make-your-electron-app-launch-1000ms-faster-32ce1e0bb52c), which was using Electron 9, which I can't use if I want to support natively Apple Silicon devices.

Do you have already tried on a similar setup, or do you have any idea on how to fix this?
Thanks in advance.

**Comment by craftzdog** [comment]
Same here.
While it downloads the compatible base snapshot (#36), the generated snapshot blob seems to be not working.
What do you think? @jkleinsc

**Comment by jkleinsc** [comment]
You need to copy both files:
`v8_context_snapshot.bin` and `snapshot_blob.bin`.  Just to verify are you doing that?  I know that M1 snapshots work in 13.x (currently in beta) and later because we added testing here: https://github.com/electron/electron/pull/24832, but its possible there are issues with older versions of Electron.

**Comment by QuiiBz** [comment]
If I remember well, I also tested copying both files and it still wasn’t working. This only happens on M1, I tested on a Windows pc and it worked great.

**Comment by craftzdog** [comment]
Thank you for the help.

I tried Electron@13.0.0-beta.4 but still doesn't work. I copied both `v8_context_snapshot.bin` and `snapshot_blob.bin`.
I found that Electron has only `v8_context_snapshot.arm64.bin` in `Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources` by default.
So, I also tried to copy `v8_context_snapshot.bin` to `v8_context_snapshot.arm64.bin` but it doesn't work.
Copying `snapshot_blob.bin` as `snapshot_blob.arm64.bin` doesn't work either.
I suspect that Electron is ignoring `snapshot_blob.bin`.

I found this comment in the build script but I have no idea how to deal with it:
https://github.com/electron/electron/blob/da8c35e3b256b4f9ad0c16edfbc2b56748b3a740/build/zip.py#L46

**Comment by jkleinsc** [comment]
I forgot that for M1/arm64 macs we changed `v8_context_snapshot.bin` to `v8_context_snapshot.arm64.bin`.  That is the proper name to use.  

Looking further into this issue, I think this may be an issue between electron-link and electron.  `snapshotResult` is defined by [electron-link](https://github.com/atom/electron-link), not by Electron or mksnapshot.

If you take a simple example that doesn't use electron-link, does that work?

Eg if you have a script like this:

```
const theAnswer = 42;
```

Is `theAnswer` defined in the snapshot?

**Comment by craftzdog** [comment]
Unfortunately, no.
I've tried to generate without using electron-link but I couldn't get `theAnswer` constant in the snapshot.

**Comment by QuiiBz** [comment]
Same here. I'm going to try with the beta versions of Electron 13 to see if there is the same issue.

**Comment by craftzdog** [comment]
Any update? @jkleinsc

**Comment by nebular** [comment]
no luck, I also think electron 12 and 13 are ignoring snapshot_blob.bin, tried to put it in ```dist/```, ```Electron.app/Contents/Frameworks/Electron\ Framework.framework/Versions/A/Resources```, ```Electron.app/Contents/Frameworks/Electron\ Framework.framework/Resources``` and basically anywhere else. Also, not sure if related, added startup flag ```--profile_deserialization```, and the things it writes about snapshot deserialization are always the same even if not copy ```snapshot_blob.bin```:
```
[Verifying snapshot checksum took 0.078 ms]
[Decompressing 266816 bytes took 0.959 ms]
[Decompressing 113048 bytes took 0.180 ms]
[Deserializing isolate (75672 bytes) took 7.959 ms]
```
Please please help :) i am running out of ideas :(

**Comment by jkleinsc** [comment]
@QuiiBz @craftzdog @nebular can you all let me know what version of electron-mksnapshot you are using? 
Also are you generating the snapshot on an m1 mac or an intel mac?

I am wondering if there is an issue where the wrong version of mksnapshot is being used for mac arm64 targets.  

FWIW when generating for mac arm64 the binary that needs to be used is the mksnapshot-vXXXXXX-darwin-arm64.zip binary (eg https://github.com/electron/electron/releases/download/untagged-8b6050841c8ed7c28a8d/mksnapshot-v13.0.0-beta.25-darwin-arm64.zip for v13 beta).  

Also you cannot use the same snapshot for both intel and arm64.  They need separate snapshots generated from separate binaries.

**Comment by nebular** [comment]
@jkleinsc thanks for the prompt reply. I am just trying to compile a simple snapshot, on Intel Mac. Made 2 tests:
```"electron": "^13.0.0-beta.18", "electron-mksnapshot": "^12.0.0"```
```"electron": "^12.0.9", "electron-mksnapshot": "^12.0.0"```
The second one should work shouldnt it? tried also 13 bcs. i'd love WASM/SIMD features.

Is there any flag or way to know if electron is indeed loading the blob? Thnks in advance !

**Comment by jkleinsc** [comment]
@nebular if you are on an intel mac targeting the snapshot to run on m1/arm64 macs you need to follow the instructions here:
https://github.com/electron/mksnapshot#macos-on-arm64
eg on an existing setup with electron-mksnapshot:
```
npm config set arch arm64
npm install
```

**Comment by nebular** [comment]
Sorry to confuse and maybe hijack the thread. I am building on Mac Intel, and my target is Mac Intel. The simplest case scenario does not work for me. As I have the luxury of your attention, could you kindly verify my setup and intentions?

1-Target is Electron 13 preferably, or Electron-12. Do snapshots work for these versions?
2-mksnapshot-v12.0.0 is right for Electron-12.0.x. And 13? In the repo only up to version 11 seem available.
3-I am supposed to "replace" snapshot-blob.bin with the new one, however in that folder there is only the snapshot-context-x86/64. Is this right?

Thanks so much for your time.

**Comment by jkleinsc** [comment]
@nebular snapshots do work for 12 and 13
mksnapshot-v12.0.0 is available for 12; 13 will be available this week when 13 is released.

The folder that the 2 generated files should be placed in is:
Electron.app/Contents/Frameworks/Electron Framework.framework/Resources.  There may or may not already be a snapshot_blob.bin file in that directory.

**Comment by nebular** [comment]
Thanks for the very good news in the answers.

I feel stupid not getting this to work. I have created an empty project with one liners and nothing:
```
"dependencies": {
    "electron": "^12.0.9",
    "electron-mksnapshot": "^12.0.0"
  }
```

root.js:
```
var ROOT = "YIKES";
```

main.js
```
console.log(typeof ROOT)
```
command:
´´´
./node_modules/electron-mksnapshot/bin/mksnapshot --no-use-ic root.js --target-arch=x86_64 --target-os=darwin --startup-blob=snapshot_blob.bin 
´´´
only generates snapshot_blob.bin

I copy it 
```
cp -v *.bin ./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron\ Framework.framework/Resources/
````

And result is undefined.

**Comment by QuiiBz** [comment]
> @QuiiBz @craftzdog @nebular can you all let me know what version of electron-mksnapshot you are using?
> Also are you generating the snapshot on an m1 mac or an intel mac?

I used `mksnapshot@12.0.0` and `electron@12.0.0`, on an M1 mac. As mentioned @nebular, I also think electron is ignoring `snapshot_blob.bin`.

**Comment by jkleinsc** [comment]
@nebular if you are calling the mksnapshot binary directly, there are specific arguments needed to match electron.  You can find those args listed in bin/mksnapshot_args or you can use mksnapshot.js included in this module and it will automatically include the proper args.  For example you can run something like:
```
node mksnapshot.js `pwd`/hello.js --output_dir `pwd`/gen
```

FWIW... we are testing this in CI in 13 on both intel and m1 macs and it works fine.

**Comment by nebular** [comment]
THANKS SO MUCH !!! it worked.

Just one thing, I got it to work with Electron-12.0.0. Electron-12.0.9 complains about Snapshot Version Mismatch (by a little).  

A couple things that confused me, hope I can help others:
- make sure the paths to mksnapshot are not relative
- mksnapshot generates ```v8_context_snapshot.bin```, that I had to rename to ```v8_context_snapshot.x86_64.bin```

I am so happy. Keep up the good work. Electron and its developers rock !!!

**Comment by QuiiBz** [comment]
> THANKS SO MUCH !!! it worked.
> 
> Just one thing, I got it to work with Electron-12.0.0. Electron-12.0.9 complains about Snapshot Version Mismatch (by a little).
> 
> A couple things that confused me, hope I can help others that land here:
> 
> * check the paths to _**mksnapshot.js**_ are not relative
> * mksnapshot generates `v8_context_snapshot.bin`, that I had to rename to `v8_context_snapshot.x86_64.bin`
> * And specially, tutorials on the net mostly refer to the raw mksnapshot and outdated material. make sure you are running mksnapshot.js and not mksnapshot.
> 
> I am so happy. Keep up the good work. Electron and its developers rock !!!

Could you share an example repo? That would help us and others!

**Comment by nebular** [comment]
absolutely, i am in debt. will post it very soon.

**Comment by QuiiBz** [comment]
Thanks for sharing this, but I'm still not able to run the application. Here is the output when I start the electron app from your repo. As you can see, I still get `undefined` for any stuff coming from the snapshot.

<img width="785" alt="Screenshot 2021-05-25 at 08 53 13" src="https://user-images.githubusercontent.com/43268759/119452506-be171700-bd36-11eb-8570-72bffd3c1947.png">

As a reminder, I'm using an M1 mac, and used the `snapshot-osx-arm64` script.

**Comment by nebular** [comment]
Sorry to hear! If in ```./node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Resources``` you have the ```snapshot_blob.bin``` and the context with ```.arm64.bin``` extension and it doesn´t work it´s probably related to other things. Script just makes sure the steps are as designed by the developers.  Maybe @jkleinsc  can confirm if the platform suffix "arm64" is right, but  as I don´t have a M1 I can´t test it further.

**Comment by jkleinsc** [comment]
@QuiiBz I have been doing some testing and while I can't yet 100% verify this, it appears that our testing builds for arm64/m1 macs work properly with snapshots, but release builds (eg the ones that are in npm) seem to have problems with snapshots.  Once I do some additional testing I'll reply in this issue with an update.

**Comment by jkleinsc** [comment]
I found the issue.  It will require new releases of Electron as well as new versions of this module.  I should have a fix up shortly.

**Comment by QuiiBz** [comment]
> I found the issue. It will require new releases of Electron as well as new versions of this module. I should have a fix up shortly.

Thanks a lot, happy to hear that! Do you need any help on this module?

**Comment by nebular** [comment]
coool  !! :) cant wait for mksnapshot 13.0 :)

**Comment by craftzdog** [comment]
It worked!!! Thanks so much @jkleinsc 

<img width="388" alt="Screen Shot 2021-05-27 at 10 58 36" src="https://user-images.githubusercontent.com/1332805/119755302-c610bb80-bedc-11eb-85c4-090d580f7729.png">
