### ISSUE TITLE
Timeline of mksnapshot version matching electron v12.0.1

### ISSUE THREAD

**Issue by thlorenz** [electron/mksnapshot#38]
Given that electron v12.0.1 is out a while now I was wondering when a matching mksnapshot version will be provided?
Also I'm a bit confused since there seems to be no matching release/tag in this repo for that [12.0.0 npm version](https://www.npmjs.com/package/electron-mksnapshot/v/12.0.0).

LMK if I can help here in any way, I'm just not aware at all how these binaries get built.

**Comment by jkleinsc** [comment]
I just forgot to label GitHub with the 12.0.0 release.  You can use 12.0.0 for 12.0.1.

**Comment by jkleinsc** [comment]
I should also mention I did update GitHub: https://github.com/electron/mksnapshot/releases/tag/v12.0.0
