### ISSUE TITLE
Generate Snapshot-Blob for win32 from darwin?

### ISSUE THREAD

**Issue by nebular** [electron/mksnapshot#45]
Hi. Congratulations on the release of v13. It rocks!

I want to generate the blob files for win32 and darwin, both for x86_64 arch. Tried the following:
- use same files as platform is x86_64 => works in mac, "objects not found" in windows (and helper processes hang).
- set "--target_os=win" but it is overwritten each npm install with the current platform
- npm config set platform=win32 => downloads the "mksnapshot.exe" that cannot run in OSX

So, how would I do it? I read somewhere that the file "bin/embedded.S" is platform dependent. i tried to overwrite the mac version with the one from win32 but it also didn´t work..

**Comment by theArina** [comment]
idk if it helps, but here 
https://github.com/electron/mksnapshot/issues/40#issuecomment-847100011

**Comment by jkleinsc** [comment]
As @theArina mentioned, [you cannot ](https://github.com/electron/mksnapshot/issues/40#issuecomment-847100011) do this on darwin. The snapshot needs to be generated on the same OS that you are targeting. For example for a Windows app, you would need to generate the snapshot on a Windows OS.
