### ISSUE TITLE
Doesn't appear to work with Electron 17.0.1

### ISSUE THREAD

**Issue by anonmate** [electron/mksnapshot#56]
I used mksnapshot v17.0.0 for electron v17.0.1 but it's not working. Maybe 2 versions need to be the same?

Our project relies on Electron always being up to date for security – do we have to rely on maintainers to make sure it's always compatible or is there something we can do to automate that?

**Comment by jkleinsc** [comment]
@anonmate can you provide more details as to what is not working?  How are you generating the snapshot?  Do you see any error messages?

**Comment by anonmate** [comment]
> @anonmate can you provide more details as to what is not working? How are you generating the snapshot? Do you see any error messages?

I'll have to get some info from the team – thanks for the quick reply!

**Comment by goldenstar07** [comment]
Hello, @jkleinsc. I'm a team member of @anonmate. This module is very useful. 

I'll explain the issue that we encounted.

os: win10 x64
electron: 17.1.1 or 17.0.1
mksnapshot: 17.0.0 (latest)

I made v8 snapshot using this script.
https://github.com/inkdropapp/electron-v8snapshots-example/blob/master/tools/create-v8-snapshots.js

I got snapshot_blob.bin and v8_context_snapshot.bin files and copied them to the node_modules/electron/dist.
I run the project and got  the following issues.

```
#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 9.8.177.11-electron.0
#    Snapshot version: 9.8.177.9-electron.0
# The snapshot consists of 4182832 bytes and contains 3 context(s).
#
#
#
#FailureMessage Object: 0000003170FFE9E0
 1: 00007FF72ECA192D node_api_get_module_file_name+18445
 2: 00007FF732016C5E GetMainTargetServices+1569870
 3: 00007FF72D848D45 v8::internal::OSROptimizedCodeCache::ClearEntry+301237
 7: 00007FF72CF12B7B std::__1::__vector_base<v8::CpuProfileDeoptInfo,std::__1::allocator<v8::CpuProfileDeoptInfo> 
>::__alloc+48763
 8: 00007FF72DBAB74C node::GetEnvironmentIsolateData+921564                                                       allocator+11385    
 9: 00007FF72DBAF2DF node::GetEnvironmentIsolateData+936815                                                       >::__alloc+48763   
10: 00007FF72DBAAD58 node::GetEnvironmentIsolateData+919016
11: 00007FF72D09652E v8::SharedMemoryStatistics::read_only_space_size+10078
12: 00007FF72D0978F3 v8::Isolate::GetNumberOfDataSlots+4499
13: 00007FF72D0972AD v8::Isolate::GetNumberOfDataSlots+2893
14: 00007FF72D0935DC std::__1::vector<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame> >::begin+483612
15: 00007FF72D093DA4 std::__1::vector<v8::CpuProfileDeoptFrame,std::__1::allocator<v8::CpuProfileDeoptFrame> >::begin+483612gin+485604                                                                                                        gin+485604
16: 00007FF72CE37D6D cppgc::SourceLocation::SourceLocation+47021
17: 00007FF7307C9612 Cr_z_crc32+4589730
18: 00007FFED0477034 BaseThreadInitThunk+20
19: 00007FFED12C2651 RtlUserThreadStart+33
error Command failed with exit code 2147483651.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Seems not matching electrion version and mksnapshot version.

In the case of using electron v17.0.0 and mksnapshot v17.0.0 I could run project successfully.

thank you.
