### ISSUE TITLE
Will this concept carry through in 2.0.0?

### ISSUE THREAD

**Issue by smotaal** [electron/mksnapshot#7]
I'm discovering that there has not been any mksnapshot binaries for any of the 2.0.0 prereleases. I just wanted to check if mksnapshot is still in play moving forward (considering --experimental-modules and related implications).

Thanks!

**Comment by jkleinsc** [comment]
@smotaal yes.  There will be a 2.0.0 release shortly

**Comment by smotaal** [comment]
Cheers 👍
